copy /Y %ILX_CODE%\lib64\ACE_TAO\lib\*.dll %ILX_BIN%
copy /Y %ILX_CODE%\lib64\ActiveMQ\*.dll %ILX_BIN%
copy /Y %ILX_CODE%\lib64\ARCSDK_10\*.dll %ILX_BIN%
copy /Y %ILX_CODE%\lib64\CodeJock\lib\vc150x64\*.dll %ILX_BIN%
copy /Y %ILX_CODE%\lib64\Stingray\Lib\vc14\x64\*.dll %ILX_BIN%
copy /Y %ILX_CODE%\lib64\Vtk\bin\*.dll %ILX_BIN%
copy /Y %ILX_CODE%\lib\bmgc32.dll %ILX_BIN%
copy /Y %ILX_CODE%\lib\bmproj32.dll %ILX_BIN%
copy /Y %ILX_CODE%\lib\BMTransf.dll %ILX_BIN%